#!/usr/bin/env python3
"""Regenerate weights.hpp and the golden test vectors from the v1 mnist.h.

v1 stored every weight matrix padded out to a width of 256, because Vec_t was
a fixed 256-wide DataPack. Layer 3 is 256x10, so 96% of what it stored was
zero padding. Here each matrix keeps its natural width.

Deriving from mnist.h (rather than re-running the Vitis AI dump) means the new
version is numerically identical to v1 by construction -- any output difference
is a bug in the new kernel, not a different quantisation.
"""

import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
V1_MNIST_H = ROOT.parent / "src" / "mnist.h"
X_TEST_NPY = ROOT.parent / "pynq" / "x_test.npy"
Y_TEST_NPY = ROOT.parent / "pynq" / "y_test.npy"

LAYERS = [784, 128, 256, 10]
PADDED_WIDTH = 256


def parse_c_arrays(path):
    """Pull every `static const int8_t name[N] = {...}` out of a C header."""
    text = path.read_text(encoding="utf-8", errors="replace")
    arrays = {}
    for m in re.finditer(r"int8_t\s+(\w+)\s*\[\s*(\d+)\s*\]\s*=\s*\{", text):
        name, declared = m.group(1), int(m.group(2))
        depth, i = 1, m.end()
        while depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        values = np.array(
            [int(v) for v in text[m.end():i - 1].replace("\n", "").split(",")],
            dtype=np.int8,
        )
        if values.size != declared:
            raise ValueError(f"{name}: declared {declared}, parsed {values.size}")
        arrays[name] = values
    return arrays


def emit_array(name, values, per_line=32):
    out = [f"static const int8_t {name}[{values.size}] = {{"]
    for start in range(0, values.size, per_line):
        chunk = ",".join(str(int(v)) for v in values[start:start + per_line])
        out.append("    " + chunk + ("," if start + per_line < values.size else ""))
    out.append("};")
    return "\n".join(out)


def emit_matrix(name, matrix):
    """Emit a 2-D array so HLS can ARRAY_RESHAPE dim=2 into one word per row."""
    rows, cols = matrix.shape
    out = [f"static const int8_t {name}[{rows}][{cols}] = {{"]
    for r in range(rows):
        body = ",".join(str(int(v)) for v in matrix[r])
        out.append("    {" + body + ("}," if r + 1 < rows else "}"))
    out.append("};")
    return "\n".join(out)


def main():
    if not V1_MNIST_H.exists():
        sys.exit(f"missing {V1_MNIST_H}")
    arrays = parse_c_arrays(V1_MNIST_H)

    # Strip the padding: [K][256] -> [K][M].
    weights = []
    for idx in range(3):
        k, m = LAYERS[idx], LAYERS[idx + 1]
        padded = arrays[f"weights{idx + 1}"].reshape(-1, PADDED_WIDTH)
        if padded.shape[0] != k:
            raise ValueError(f"weights{idx+1}: expected {k} rows, got {padded.shape[0]}")
        if np.any(padded[:, m:] != 0):
            raise ValueError(f"weights{idx+1}: padding region is not all zero")
        weights.append(padded[:, :m])

    bias, scales = arrays["bias"], arrays["scales"]
    saved = sum(w.size for w in weights)
    original = sum(arrays[f"weights{i+1}"].size for i in range(3))
    print(f"weights: {original} -> {saved} bytes ({100 * (1 - saved / original):.0f}% padding removed)")

    header = ROOT / "src" / "weights.hpp"
    parts = [
        "// Generated by scripts/gen_weights.py from MNIST_HLS/src/mnist.h -- do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for idx, w in enumerate(weights):
        parts.append(f"// layer {idx + 1}: [inputs][outputs]; one row is read per cycle")
        parts.append(emit_matrix(f"weights{idx + 1}", w))
        parts.append("")
    parts.append(emit_array("bias", bias))
    parts.append("")
    parts.append(emit_array("scales", scales))
    parts.append("")
    header.write_text("\n".join(parts))
    print(f"wrote {header} ({header.stat().st_size // 1024} KiB)")

    # Golden vectors. The reference is deliberately plain numpy in int64 so it
    # cannot silently share an overflow bug with the int16 hardware accumulator.
    x = (np.load(X_TEST_NPY) // 32).astype(np.int8)
    y = np.load(Y_TEST_NPY).astype(np.uint8)
    x = x.reshape(len(x), -1)

    acc_peak = 0
    preds = np.empty(len(x), dtype=np.int8)
    data = x.astype(np.int64)
    for idx, w in enumerate(weights):
        acc = data @ w.astype(np.int64)
        acc_peak = max(acc_peak, int(np.abs(acc).max()))
        data = (acc + bias[sum(LAYERS[1:idx + 1]):sum(LAYERS[1:idx + 2])].astype(np.int64))
        data >>= int(scales[idx])
        if idx != 2:
            data = np.maximum(data, 0)
    preds[:] = np.argmax(data, axis=1).astype(np.int8)

    accuracy = (preds == y).mean()
    print(f"golden accuracy: {accuracy:.4f}")
    print(f"peak |accumulator| before bias: {acc_peak} (int16 max 32767)")
    if acc_peak > 32767:
        print("WARNING: the int16 hardware accumulator would overflow on this data")

    data_dir = ROOT / "test" / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "x_test_i8.bin").write_bytes(x.astype(np.int8).tobytes())
    (data_dir / "y_test_u8.bin").write_bytes(y.tobytes())
    (data_dir / "golden_pred_i8.bin").write_bytes(preds.tobytes())
    print(f"wrote {len(x)} test vectors to {data_dir}")


if __name__ == "__main__":
    main()
